# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstMainWin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(787, 628)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(787, 628))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_control = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_control.setObjectName("groupBox_control")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_control)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_control)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.frequency_spinBox = QtWidgets.QSpinBox(self.groupBox_control)
        self.frequency_spinBox.setPrefix("")
        self.frequency_spinBox.setMaximum(9999)
        self.frequency_spinBox.setObjectName("frequency_spinBox")
        self.horizontalLayout.addWidget(self.frequency_spinBox)
        self.frequency_pushButton = QtWidgets.QPushButton(self.groupBox_control)
        self.frequency_pushButton.setObjectName("frequency_pushButton")
        self.horizontalLayout.addWidget(self.frequency_pushButton)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_control)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.synchronization_inside_radioButton = QtWidgets.QRadioButton(self.groupBox_control)
        self.synchronization_inside_radioButton.setChecked(True)
        self.synchronization_inside_radioButton.setObjectName("synchronization_inside_radioButton")
        self.horizontalLayout_2.addWidget(self.synchronization_inside_radioButton)
        self.synchronization_outside_radioButton = QtWidgets.QRadioButton(self.groupBox_control)
        self.synchronization_outside_radioButton.setObjectName("synchronization_outside_radioButton")
        self.horizontalLayout_2.addWidget(self.synchronization_outside_radioButton)
        self.synchronization_pushButton = QtWidgets.QPushButton(self.groupBox_control)
        self.synchronization_pushButton.setObjectName("synchronization_pushButton")
        self.horizontalLayout_2.addWidget(self.synchronization_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addWidget(self.groupBox_control, 0, 1, 1, 1)
        self.groupBox_receive = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_receive.setObjectName("groupBox_receive")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_receive)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.groupBox_receive)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10, 0, QtCore.Qt.AlignLeft)
        self.sourceIP_comboBox = QtWidgets.QComboBox(self.groupBox_receive)
        self.sourceIP_comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.sourceIP_comboBox.setEditable(False)
        self.sourceIP_comboBox.setCurrentText("")
        self.sourceIP_comboBox.setObjectName("sourceIP_comboBox")
        self.horizontalLayout_7.addWidget(self.sourceIP_comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_11 = QtWidgets.QLabel(self.groupBox_receive)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_15.addWidget(self.label_11)
        self.testDataReceive_label = QtWidgets.QLabel(self.groupBox_receive)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testDataReceive_label.sizePolicy().hasHeightForWidth())
        self.testDataReceive_label.setSizePolicy(sizePolicy)
        self.testDataReceive_label.setObjectName("testDataReceive_label")
        self.horizontalLayout_15.addWidget(self.testDataReceive_label)
        self.testDataReceive_clear_pushButton = QtWidgets.QPushButton(self.groupBox_receive)
        self.testDataReceive_clear_pushButton.setObjectName("testDataReceive_clear_pushButton")
        self.horizontalLayout_15.addWidget(self.testDataReceive_clear_pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.label_13 = QtWidgets.QLabel(self.groupBox_receive)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.textReceive_plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_receive)
        self.textReceive_plainTextEdit.setObjectName("textReceive_plainTextEdit")
        self.verticalLayout_4.addWidget(self.textReceive_plainTextEdit)
        self.label_14 = QtWidgets.QLabel(self.groupBox_receive)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.groupBox_receive)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.fileReceive_plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_receive)
        self.fileReceive_plainTextEdit.setObjectName("fileReceive_plainTextEdit")
        self.verticalLayout_4.addWidget(self.fileReceive_plainTextEdit)
        self.gridLayout.addWidget(self.groupBox_receive, 1, 1, 1, 1)
        self.groupBox_netStatus = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_netStatus.setObjectName("groupBox_netStatus")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_netStatus)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.netStatus_clistView = QtWidgets.QListView(self.groupBox_netStatus)
        self.netStatus_clistView.setObjectName("netStatus_clistView")
        self.horizontalLayout_13.addWidget(self.netStatus_clistView)
        self.netStatus_graphicsView = QtWidgets.QGraphicsView(self.groupBox_netStatus)
        self.netStatus_graphicsView.setObjectName("netStatus_graphicsView")
        self.horizontalLayout_13.addWidget(self.netStatus_graphicsView)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 3)
        self.gridLayout.addWidget(self.groupBox_netStatus, 0, 0, 1, 1)
        self.groupBox_send = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_send.setObjectName("groupBox_send")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_send)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.IP1_radioButton = QtWidgets.QRadioButton(self.groupBox_send)
        self.IP1_radioButton.setChecked(True)
        self.IP1_radioButton.setObjectName("IP1_radioButton")
        self.verticalLayout_2.addWidget(self.IP1_radioButton)
        self.IP2_radioButton = QtWidgets.QRadioButton(self.groupBox_send)
        self.IP2_radioButton.setObjectName("IP2_radioButton")
        self.verticalLayout_2.addWidget(self.IP2_radioButton)
        self.IP3_radioButton = QtWidgets.QRadioButton(self.groupBox_send)
        self.IP3_radioButton.setObjectName("IP3_radioButton")
        self.verticalLayout_2.addWidget(self.IP3_radioButton)
        self.IP4_radioButton = QtWidgets.QRadioButton(self.groupBox_send)
        self.IP4_radioButton.setObjectName("IP4_radioButton")
        self.verticalLayout_2.addWidget(self.IP4_radioButton)
        self.IP5_radioButton = QtWidgets.QRadioButton(self.groupBox_send)
        self.IP5_radioButton.setObjectName("IP5_radioButton")
        self.verticalLayout_2.addWidget(self.IP5_radioButton)
        self.IP6_radioButton = QtWidgets.QRadioButton(self.groupBox_send)
        self.IP6_radioButton.setObjectName("IP6_radioButton")
        self.verticalLayout_2.addWidget(self.IP6_radioButton)
        self.broadcast_radioButton = QtWidgets.QRadioButton(self.groupBox_send)
        self.broadcast_radioButton.setObjectName("broadcast_radioButton")
        self.verticalLayout_2.addWidget(self.broadcast_radioButton)
        self.horizontalLayout_14.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_send)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_10.addWidget(self.label_18)
        self.testDataSend_len_spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.testDataSend_len_spinBox.setPrefix("")
        self.testDataSend_len_spinBox.setMaximum(9999)
        self.testDataSend_len_spinBox.setProperty("value", 512)
        self.testDataSend_len_spinBox.setObjectName("testDataSend_len_spinBox")
        self.horizontalLayout_10.addWidget(self.testDataSend_len_spinBox)
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_10.addWidget(self.label_19)
        self.testDataSend_frequency_spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.testDataSend_frequency_spinBox.setPrefix("")
        self.testDataSend_frequency_spinBox.setMaximum(9999)
        self.testDataSend_frequency_spinBox.setProperty("value", 100)
        self.testDataSend_frequency_spinBox.setObjectName("testDataSend_frequency_spinBox")
        self.horizontalLayout_10.addWidget(self.testDataSend_frequency_spinBox)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.testDataSend_start_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.testDataSend_start_pushButton.setObjectName("testDataSend_start_pushButton")
        self.horizontalLayout_11.addWidget(self.testDataSend_start_pushButton)
        self.testDataSend_label = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testDataSend_label.sizePolicy().hasHeightForWidth())
        self.testDataSend_label.setSizePolicy(sizePolicy)
        self.testDataSend_label.setObjectName("testDataSend_label")
        self.horizontalLayout_11.addWidget(self.testDataSend_label)
        self.testDataSend_stop_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.testDataSend_stop_pushButton.setObjectName("testDataSend_stop_pushButton")
        self.horizontalLayout_11.addWidget(self.testDataSend_stop_pushButton)
        self.testDataSend_clear_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.testDataSend_clear_pushButton.setObjectName("testDataSend_clear_pushButton")
        self.horizontalLayout_11.addWidget(self.testDataSend_clear_pushButton)
        self.horizontalLayout_11.setStretch(2, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox_send)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.textSend_plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_send)
        self.textSend_plainTextEdit.setObjectName("textSend_plainTextEdit")
        self.horizontalLayout_8.addWidget(self.textSend_plainTextEdit)
        self.textSend_pushButton = QtWidgets.QPushButton(self.groupBox_send)
        self.textSend_pushButton.setObjectName("textSend_pushButton")
        self.horizontalLayout_8.addWidget(self.textSend_pushButton)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(2, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_17 = QtWidgets.QLabel(self.groupBox_send)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_9.addWidget(self.label_17)
        self.audioSend_start_pushButton = QtWidgets.QPushButton(self.groupBox_send)
        self.audioSend_start_pushButton.setObjectName("audioSend_start_pushButton")
        self.horizontalLayout_9.addWidget(self.audioSend_start_pushButton)
        self.audioSend_stop_pushButton = QtWidgets.QPushButton(self.groupBox_send)
        self.audioSend_stop_pushButton.setObjectName("audioSend_stop_pushButton")
        self.horizontalLayout_9.addWidget(self.audioSend_stop_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_send)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout.setObjectName("formLayout")
        self.fileSend_chooseFile_pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.fileSend_chooseFile_pushButton.setObjectName("fileSend_chooseFile_pushButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fileSend_chooseFile_pushButton)
        self.fileSend_fileName_plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.fileSend_fileName_plainTextEdit.setObjectName("fileSend_fileName_plainTextEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fileSend_fileName_plainTextEdit)
        self.fileSend_pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.fileSend_pushButton.setObjectName("fileSend_pushButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fileSend_pushButton)
        self.fileSend_progressBar = QtWidgets.QProgressBar(self.groupBox_4)
        self.fileSend_progressBar.setProperty("value", 24)
        self.fileSend_progressBar.setObjectName("fileSend_progressBar")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fileSend_progressBar)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.horizontalLayout_14.addLayout(self.verticalLayout_6)
        self.gridLayout.addWidget(self.groupBox_send, 1, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QBL测试程序"))
        self.groupBox_control.setTitle(_translate("MainWindow", "控制"))
        self.label.setText(_translate("MainWindow", "频率:"))
        self.frequency_spinBox.setSuffix(_translate("MainWindow", "MHZ"))
        self.frequency_pushButton.setText(_translate("MainWindow", "下发"))
        self.label_2.setText(_translate("MainWindow", "同步:"))
        self.synchronization_inside_radioButton.setText(_translate("MainWindow", "内同步"))
        self.synchronization_outside_radioButton.setText(_translate("MainWindow", "外同步"))
        self.synchronization_pushButton.setText(_translate("MainWindow", "下发"))
        self.groupBox_receive.setTitle(_translate("MainWindow", "业务数据-收"))
        self.label_10.setText(_translate("MainWindow", "源地址:"))
        self.label_11.setText(_translate("MainWindow", "测试数据:"))
        self.testDataReceive_label.setText(_translate("MainWindow", "158Bytes"))
        self.testDataReceive_clear_pushButton.setText(_translate("MainWindow", "清空"))
        self.label_13.setText(_translate("MainWindow", "报文:"))
        self.label_14.setText(_translate("MainWindow", "语音:   ..."))
        self.label_15.setText(_translate("MainWindow", "文件:"))
        self.groupBox_netStatus.setTitle(_translate("MainWindow", "网络拓扑状态"))
        self.groupBox_send.setTitle(_translate("MainWindow", "业务测试-发"))
        self.IP1_radioButton.setText(_translate("MainWindow", "192.168.3.11"))
        self.IP2_radioButton.setText(_translate("MainWindow", "192.168.3.12"))
        self.IP3_radioButton.setText(_translate("MainWindow", "192.168.3.13"))
        self.IP4_radioButton.setText(_translate("MainWindow", "192.168.3.14"))
        self.IP5_radioButton.setText(_translate("MainWindow", "192.168.3.15"))
        self.IP6_radioButton.setText(_translate("MainWindow", "192.168.3.16"))
        self.broadcast_radioButton.setText(_translate("MainWindow", "广播"))
        self.groupBox_3.setTitle(_translate("MainWindow", "测试数据"))
        self.label_18.setText(_translate("MainWindow", "单帧长度:"))
        self.testDataSend_len_spinBox.setSuffix(_translate("MainWindow", "Bytes"))
        self.label_19.setText(_translate("MainWindow", "发送频率:"))
        self.testDataSend_frequency_spinBox.setSuffix(_translate("MainWindow", "次/s"))
        self.testDataSend_start_pushButton.setText(_translate("MainWindow", "开始"))
        self.testDataSend_label.setText(_translate("MainWindow", "158Bytes"))
        self.testDataSend_stop_pushButton.setText(_translate("MainWindow", "停止"))
        self.testDataSend_clear_pushButton.setText(_translate("MainWindow", "清空"))
        self.label_8.setText(_translate("MainWindow", "报文:"))
        self.textSend_pushButton.setText(_translate("MainWindow", "发送"))
        self.label_17.setText(_translate("MainWindow", "语音:"))
        self.audioSend_start_pushButton.setText(_translate("MainWindow", "开始"))
        self.audioSend_stop_pushButton.setText(_translate("MainWindow", "停止"))
        self.groupBox_4.setTitle(_translate("MainWindow", "文件发送"))
        self.fileSend_chooseFile_pushButton.setText(_translate("MainWindow", "选取文件"))
        self.fileSend_pushButton.setText(_translate("MainWindow", "发送"))
